ci: Add gh workflow job for linting the terratest tests

diff --git a/.github/workflows/terraform-ci-recipes.yml b/.github/workflows/terraform-ci-recipes.yml
--- a/.github/workflows/terraform-ci-recipes.yml
+++ b/.github/workflows/terraform-ci-recipes.yml
@@ -32,6 +32,7 @@ jobs:
         strategy:
             matrix:
                 recipe: ${{fromJson(needs.set_up_recipes_job.outputs.matrix)}}
+
         steps:
             - uses: actions/checkout@v4
 
@@ -40,22 +41,25 @@ jobs:
 
             - name: Terraform Init
               run: |
-                  cd ${{ matrix.recipe }}
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
                   terraform init
+
+                  # The remaining steps should be updated in the same way, with:
+                  # cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
 
             - name: Terraform Fmt
               run: |
-                  cd ${{ matrix.recipe }}
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
                   terraform fmt -check -recursive
 
             - name: Terraform Validate
               run: |
-                  cd ${{ matrix.recipe }}
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
                   terraform validate
 
             - name: Validate Terraform docs file
               run: |
-                  cd ${{ matrix.recipe }}
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
                   if [ -f .terraform-docs.yml ]; then
                     echo "terraform-docs configuration file found"
                     cat .terraform-docs.yml
@@ -66,24 +70,24 @@ jobs:
 
             - name: Validate TFLint file
               run: |
-                  cd ${{ matrix.recipe }}
-                  if [ -f .tflint.hcl ]; then
-                    echo "TFLint configuration file found"
-                    cat .tflint.hcl
-                  else
-                    echo "Error: .tflint.hcl file not found in ${{ matrix.recipe }}"
-                    exit 1
-                  fi
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
+                    if [ -f .tflint.hcl ]; then
+                      echo "TFLint configuration file found"
+                      cat .tflint.hcl
+                    else
+                      echo "Error: .tflint.hcl file not found in ${{ matrix.recipe }}"
+                      exit 1
+                    fi
 
             - name: Check for README.md file
               run: |
-                  cd ${{ matrix.recipe }}
-                  if [ -f README.md ]; then
-                    echo "README.md file found"
-                  else
-                    echo "Error: README.md file not found in ${{ matrix.recipe }}"
-                    exit 1
-                  fi
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
+                    if [ -f README.md ]; then
+                      echo "README.md file found"
+                    else
+                      echo "Error: README.md file not found in ${{ matrix.recipe }}"
+                      exit 1
+                    fi
 
             - name: Terraform TFLintSetup
               uses: terraform-linters/setup-tflint@v1
@@ -92,8 +96,8 @@ jobs:
 
             - name: TFLint Run
               run: |
-                  cd ${{ matrix.recipe }}
-                  tflint --version
-                  tflint --init
-                  tflint --disable-rule=terraform_module_pinned_source
-                  tflint
+                  cd ${{ env.TF_ROOT }}/${{ matrix.recipe }}
+                    tflint --version
+                    tflint --init
+                    tflint --disable-rule=terraform_module_pinned_source
+                    tflint
